### ISSUE TITLE
Feature Request - Model Your own DSL then build related Custom Model Scaffold

### ISSUE THREAD

**Issue by mariusvrstr** [IntentSoftware/Intent.Modules#120]
Right now the Intent Model seems pretty fixed, powerful as its notation is pretty generic across many DSL's. I.e. classes, properties., etc. This means you can extend your DSL with custom stereo types in custom modules but you are still confined to the current DSL.

Imaging Intent having two flavors Intent Architect and Intent Developer each solving a different problem a) Architect and design your templatized solutions using a custom DSL (or using the default) and a corresponding module
b) Developer use specialized modules with associated DSL's to more specifically model for modules

**In short**
Using Intent Architects can crate their own custom visual DSLs (You DSL views will show dynamically based on selected Modules) that the developers will then later use to model with after selecting the new module.

**Lifecylce**

1. Using Intent Architect >> Create _custom DSL in GUI with a module scaffolding code_ output with typesafe access to the new DSL
2.Using Visual Studio u_pdate the module scaffolding to automate a certain pattern_ i.e. create a SSRS report asking things like Report (not class) etc
3.Submit / Host your packaged Intent Module for use in any project
4.. Using Intent Developer >> Add the new module (Which also add a _new DSL perspective with its own notations_) then model within the custom DSL

Just an idea to open your product for limitless applications and more customization DSL modeling capabilities.

**Comment by garethbaars** [comment]
Hi @mariusvrstr,

This is a great idea and something we would definitely want to do. I've added it to the road map.

Regarding new DSLs, what types of new DSLs would you plan on creating?

Cheers
Gareth

**Comment by dandrejvv** [comment]
Hi @mariusvrstr.
Since then we have worked on the Module Builder which features a Designer Builder that allows you to build your own designer or extend an existing one with new elements. This has already proven useful in making a Workflow designer leveraging the Class designer. 
There is also great support for cross-designer (i.e. from Domain to Services) integration with regards to referencing element types and mapping from elements. 
As for new Bounded Contexts, a new Application Template can be used where you can select the modules you wish to install. 
If you're still interested to discuss anything else, I'm happy to leave this open otherwise I would ask that we close this ticket.

**Comment by mariusvrstr** [comment]
Thanks! Great to see the feature realized.
