### ISSUE TITLE
Failed to install Intent.OutputManager.RoslynWeaver

### ISSUE THREAD

**Issue by Bishoymly** [IntentSoftware/Intent.Modules#179]
I always get this error when creating a new project or trying to install this module:

Failed to install Intent.OutputManager.RoslynWeaver 1.9.0: Unable to locate module Intent.OutputManager.RoslynWeaver 1.9.0.
--

And without it, the package Intent.RoslynWeaver.Attributes is added in all projects and the attributes are being used everywhere but it's missing the using statement for its namespace. Which is breaking the build with error:

error CS0246: The type or namespace name 'IntentManagedAttribute' could not be found (are you missing a using directive or an assembly reference?)

--

I tried downloading earlier versions of this module and tried installing Intent Architect version 1.8 and still I face the same error failing to download only this specific module Intent.OutputManager.RoslynWeaver

If I add the using statement in all files everything else work correctly until I make some changes and generate code files again.

**Comment by JonathanLydall** [comment]
Hi Bishoymly,

It is recommended to be using Intent v1.9 with the 1.9 modules. I want to find out more about how you're trying to use Intent that it's causing these issues since when I try a `Web Application ASP.NET Core` application on my side it's working fine for me.

Can you say more about the Intent application you're trying to create, is it also a `Web Application ASP.NET Core`? Also, does it seem some modules install fine while just this does not?

If you want to chat on Slack, drop an email to support@intentarchitect.com with your email address so that I can send an invite.

**Comment by JonathanLydall** [comment]
Thanks for chatting to us on Slack Bishoy, I just wanted to publicly share the outcome of the reported issue.

It appears that sometimes downloading of modules fails without good feedback in Intent Architect. To address this we will be working on improving the reliability of the module download system and the feedback provided of the downloads.

In the meantime, anyone having a similar problem can download the module at https://intentarchitect.com/downloads/Intent.OutputManager.RoslynWeaver.1.9.0.imod and place it in a folder which they can configure as a repository in Intent Architect by following the following section in our docs: https://intentarchitect.com/docs/articles/getting_started/create_your_own_module.html?origin_team=T3EHJ9LD9#52-configure-local-module-repository
