### ISSUE TITLE
Add Consumer Stereotype to Service/DTO on Creation

### ISSUE THREAD

**Issue by Carbz22** [IntentSoftware/Intent.Modules#7]
When creating a service/DTO add the consumers stereotype to the service/DTO by default.

**Comment by dandrejvv** [comment]
Since Intent Architect 2.1 there has been support for applying stereotypes automatically to user defined types. Though we didn't support it for your stereotype specifically (`Consumer`), you as a developer can now setup stereotypes yourself that would automatically get applied to your Service / DTO items
